// Separating styles into visual art styles and professional themes for targeted AI prompting.

export const artStyles = [
    '007 Golden Eye', '007 Pierce Brosnan', '007 Roger Moore', '007 Sean Connery', '007 Solace', 
    '3d-model', 'Andy Warhol', 'Art Déco (1925)', 'Art Nouveau', 'Arquivo X', 'Bauhaus (1919)', 
    'Barrados no Baile', 'Cine Citá', 'Cinematográfico', 'Claude Monet', 'Colagem', 'Comic-book', 
    'Cyberpunk', 'DC Comics', 'Da Vinci', 'Dancing Script', 'Disney - Pixar', 'Edgar Degas', 
    'Édouard Manet', 'Estilo High Society', 'Estilo Lago di Como', 'Estilo Milano 1950', 
    'Estilo Milano 1980', 'Estilo Napoli 1980', 'Estilo UX Design 2025', 'Fantasy-art', 
    'Festival de San Remo', 'Flat', 'Fotorrealista', 'FraseUrbane', 'Friends', 'Futurismo', 
    'Geométrico', 'Estilização Geométrica', 'Gossip Girl', 'Holográfico', 'Esqueceram de Mim', 
    'Isométrico', 'Jim Davis - Garfield', 'Liga da Justiça', 'Law and Order', 'Lobster', 
    'O Lobo de Wall Street', 'Luke Skywalker', 'Luxuoso', 'Maximalismo', 'Meme', 'Meme Clássico', 
    'Meme Regional Trend', 'Meme Trend', 'Menphys', 'Minimalista', 'Neo Brutalismo', 
    'Nova Trend - Trend em alta no Instagram', 'Old Money Napoli', 'Old Money New York', 
    'Paul Rand (1940)', 'Pierre-Auguste Renoir', 'Pixel Art', 'Playfair Display', 'Poético', 
    'Pop Italiano 1980', 'Pós-modernismo (década de 1970)', 'Retrô', 'Roland Garros', 
    'Roma 1980', 'Sex and the City', 'Stan Lee - Marvel', 'Star Wars', 'Star Wars 1980', 
    'Supernatural', 'Surrealismo', 'O Talentoso Ripley', 'That\'s \'70s Show', 
    'The Big Bang Theory', 'Um Maluco no Pedaço', 'Tintin - Hergé', 'Tom Cruise - Missão Impossível', 
    'Two and a Half Men', 'UX Design 2026', 'Van Gogh', 'Wiener Werkstätte (1903)'
];

const interiorDesignRooms = [
    'Banheiro (Suíte)',
    'Closet',
    'Cozinha',
    'Home Theater',
    'Lavabo',
    'Mesa de Apoio (Sala)',
    'Sala de Estar',
];

const interiorDesignThemesCasa = interiorDesignRooms.map(d => `Design de Interiores (Casa): ${d}`);
const interiorDesignThemesApto = interiorDesignRooms.map(d => `Design de Interiores (Apartamento): ${d}`);

export const professionalThemes = [
    'Adega',
    'Advocacia Família',
    'Advocacia Trabalhista',
    'Agência de Marketing Digital',
    'Agência de Viagens',
    'Aluguel de brinquedos para festa infantil',
    'Animação de festa infantil',
    'Aplicativo de Delivery',
    'Aplicativo tipo Booking',
    'Arquiteto',
    'Assessoria de Imagem Feminina',
    'Assessoria de Imagem Masculina',
    'Autoescola',
    'Barbearia',
    'Beach Tênis (Esporte)',
    'Beleza e Cosméticos',
    'Bike',
    'Cafeteria',
    'Carpintaria',
    'Chatbot',
    'Chef de Cozinha',
    'Clínica de Fisioterapia',
    'Clínica Estética',
    'Clínica Veterinária',
    'Clube de alta classe',
    'Clube de empresários de alta classe',
    'Clube de Tênis (Esporte)',
    'Coach de Carreira',
    'Concessionária de Carros',
    'Conserto de Bike',
    'Conserto de Celular',
    'Construtora',
    'Contabilidade',
    'Corretor de Imóveis',
    'Decoração',
    'Decoração de Festas',
    'Dentista',
    'Depilação Feminina',
    'Desenvolvimento Pessoal',
    'Desenvolvimento Web',
    ...interiorDesignThemesCasa,
    ...interiorDesignThemesApto,
    'Design Gráfico',
    'Design Thinking',
    'Doces para Festas',
    'E-commerce de Moda',
    'Educação',
    'Eletricista',
    'Encanador',
    'Energia Solar',
    'Engenheiro Civil',
    'Escola de Idiomas',
    'Espelhos',
    'Estúdio de Fotografia',
    'Estúdio de Tatuagem',
    'Fabricante de chalets',
    'Farmácia',
    'Festa de Casamento',
    'Festas e Eventos',
    'Filmaker',
    'Finanças Pessoais',
    'Fitness e Saúde',
    'Floricultura',
    'Fotógrafo',
    'Gastronomia',
    'Gestor de Tráfego',
    'Hamburgueria',
    'Hotelaria',
    'Imobiliária',
    'Investimentos',
    'Jardinagem',
    'Loja de Roupas',
    'Loja de Tênis (Calçados)',
    'Manicure e Pedicure',
    'Marca de Joias',
    'Marcenaria',
    'Marketing de Afiliados',
    'Mecânica de Automóveis',
    'Mercado',
    'Música',
    'Nova Loja de: Presentes (Design Autoral)',
    'Nova Marca de: Agência de Design Industrial',
    'Nova Marca de: Agência de Design UX',
    'Nova Marca de: Agência de Marketing',
    'Nova Marca de: Agência Digital',
    'Nova Marca de: Alimentos Fit',
    'Nova Marca de: Bicicleta Elétrica',
    'Nova Marca de: Bloco Ecológico para Montagem e Construção de Casas',
    'Nova Marca de: Brinquedos Educativos Infantis',
    'Nova Marca de: Brinquedos Infantis',
    'Nova Marca de: Café',
    'Nova Marca de: Casas e Construções Modulares e Industrializadas',
    'Nova Marca de: Casas Modulares (Industrializadas) para Locais Remotos',
    'Nova Marca de: Chocolate Belga',
    'Nova Marca de: Chocolates',
    'Nova Marca de: Chocolates Gianduia',
    'Nova Marca de: Chocolates Praline',
    'Nova Marca de: Cosméticos Femininos',
    'Nova Marca de: Design de Arquitetura de Prédios',
    'Nova Marca de: Design de Casas',
    'Nova Marca de: Design de Fachadas de Prédios',
    'Nova Marca de: Design de Iluminação',
    'Nova Marca de: Design de Lojas de Galeria',
    'Nova Marca de: Design de Lojas de Rua',
    'Nova Marca de: Design de Lojas de Shopping',
    'Nova Marca de: Design de Paisagismo',
    'Nova Marca de: Design de Planejados (Cozinha)',
    'Nova Marca de: Design de Planejados (Sala)',
    'Nova Marca de: Design de Planejados para Apartamento',
    'Nova Marca de: Design de Planejados para Casa',
    'Nova Marca de: Doces Italianos',
    'Nova Marca de: Doces para Franquia',
    'Nova Marca de: Equipamentos para Academia',
    'Nova Marca de: Fast Fashion Feminina',
    'Nova Marca de: Fast Fashion Masculina',
    'Nova Marca de: Gadgets para Camping',
    'Nova Marca de: Gadgets para o Jardim',
    'Nova Marca de: Gadgets com Energia Solar',
    'Nova Marca de: Meio de Transporte Individual Elétrico',
    'Nova Marca de: Mini Moto Elétrica',
    'Nova Marca de: Módulo Habitacional Industrializado para Estruturas Existentes',
    'Nova Marca de: Módulos Habitacionais (Industrializados) para Cidades Densamente Povoadas',
    'Nova Marca de: Óculos',
    'Nova Marca de: Perfumes Femininos',
    'Nova Marca de: Perfumes Masculinos',
    'Nova Marca de: Produtos Naturais',
    'Nova Marca de: Produtos Saudáveis',
    'Nova Marca de: Relógio',
    'Nova Marca de: Roupa Casual para Homem',
    'Nova Marca de: Roupa Casual para Mulher',
    'Nova Marca de: Roupa de Ciclismo Feminina',
    'Nova Marca de: Roupa de Ciclismo Masculina',
    'Nova Marca de: Roupa de Cross Fit Feminina',
    'Nova Marca de: Roupa de Cross Fit Masculina',
    'Nova Marca de: Roupa de Triathlon Masculina',
    'Nova Marca de: Roupa Fitness Feminina',
    'Nova Marca de: Roupa para Beach Tênis Feminina',
    'Nova Marca de: Roupa para Beach Tênis Masculina',
    'Nova Marca de: Salgados para Franquia',
    'Nova Marca de: Suplementação para +40',
    'Nova Marca de: Suplementação para +50',
    'Nova Marca de: Suplementos Aminoácidos',
    'Nova Marca de: Suplementos Proteína',
    'Nova Marca de: SUV',
    'Nova Marca de: Tênis (Calçados)',
    'Nutricionista',
    'Ótica',
    'Padaria',
    'Paisagismo',
    'Papelaria',
    'Personal Organizer',
    'Personal Trainer',
    'Pet Shop',
    'Pilates',
    'Pizzaria',
    'Podcast',
    'Produção de Eventos',
    'Professor Particular',
    'Psicologia',
    'Publicidade',
    'Restaurante',
    'Salão de Beleza',
    'Segurança Eletrônica',
    'Seguros',
    'Serviços de Limpeza',
    'Social Media Manager',
    'Sorveteria',
    'Startup de Tecnologia',
    'Tênis de Quadra (Esporte)',
    'Terapia Holística',
    'Turismo',
    'Yoga'
].sort((a, b) => a.localeCompare(b));

export const masterPromptText = `Você é um assistente de criação de conteúdo de IA, especializado em gerar posts para redes sociais que são visualmente atraentes e textualmente persuasivos.

Sua tarefa é processar a solicitação do usuário e gerar dois artefatos em uma única resposta:
1.  **Imagem:** Uma imagem que corresponda à "Descrição da Imagem" e aos "Estilos da Imagem" fornecidos.
2.  **Conteúdo em JSON:** Um objeto JSON que contenha textos de marketing e sugestões criativas baseadas no "Estilo do Conteúdo".

**Regras Estritas:**
- Sempre gere a imagem primeiro, antes do bloco de JSON.
- O bloco de código JSON deve ser o último elemento da sua resposta.
- O JSON deve ser válido e seguir estritamente a estrutura definida abaixo.

**Estrutura do JSON de Saída:**
\`\`\`json
{
  "postText": {
    "title": "Um título curto e impactante para o post.",
    "body": "Um texto principal para o post, com 2 a 3 frases. Use o 'Estilo do Conteúdo' como guia. Pode incluir emojis relevantes.",
    "hashtags": [
      "#hashtag1",
      "#hashtag2",
      "#hashtag3"
    ]
  },
  "strategyTip": "Uma dica de marketing ou estratégia criativa rápida e acionável relacionada ao post gerado."
}
\`\`\`

**Como Processar a Solicitação do Usuário:**
O usuário fornecerá as seguintes informações:
- **Descrição da Imagem:** O que deve estar na imagem.
- **Estilos da Imagem:** Uma lista de estilos visuais e suas ponderações (ex: "Fotorrealista (70%), Cinematográfico (30%)").
- **Estilo do Conteúdo:** O tom e a voz para o texto (ex: "Profissional e Confiável", "Divertido e Descontraído").

Aja agora. Aguardo a primeira solicitação do usuário.`;